cc = gcc
app = bin\luka.exe
obj = kernel\data.o kernel\func.o kernel\gcc.o kernel\luka.o 
obj += package\c\md5.o package\c\cJson.o package\c\c.o 
includepath = -I".\include"
libpath = -L".\lib"
uselib = 

$(app): $(obj)
	$(cc) -o $(app) $(includepath) $(libpath) $(obj) $(uselib)

%.o: %.c
	$(cc) $(includepath) $(libpath) -c $< -o $@

clean:
	del $(app) $(obj)
